import time
import json
from typing import Tuple, Optional

import cv2
import numpy as np

from navigation_simulator import NavigationSimulator


class MouseNavigationSimulator(NavigationSimulator):
    """
    Simulates IMU + GPS navigation using mouse input.

    Trakcs true mouse position.
    Velocity and acceleration are estimated using numerical differentiation.

    Sensor readings are generated by adding noise to true values.
    """
    def __init__(self,
        gps_freq: float = 2.0,
        gps_noise_std: float = 30.0,
        imu_noise_std: float = 3.0,
        width: int = 800,
        height: int = 600
        ):
        super().__init__(width=width, height=height)
        
        self.last_pos = self.true_pos.copy()
        self.last_vel = np.zeros(2)
        self.last_time = time.time()
        
        self.true_vel = np.zeros(2)
        self.true_accel = np.zeros(2)

        self.gps_freq = gps_freq
        self.gps_noise_std = gps_noise_std
        self.gps_last_time = time.time()
        self.imu_noise_std = imu_noise_std

        # Visualization setup
        cv2.namedWindow("IMU + GPS Navigation Simulation")
        cv2.setMouseCallback("IMU + GPS Navigation Simulation", self._mouse_callback, self)
        
        # Recording
        self.records = []
    
    def _mouse_callback(self, event, x, y, flags, param):
        if event == cv2.EVENT_MOUSEMOVE:
            param.true_pos = np.array([x, y], dtype=float)


    def update(self) -> float:
        now = time.time()
        dt = now - self.last_time
        self.last_time = now

        # Numerical differentiation to get velocity (pixels / sec)
        self.true_vel = (self.true_pos - self.last_pos) / dt

        # Numerical differentiation to get acceleration (pixels / sec^2)
        self.true_accel = (self.true_vel - self.last_vel) / dt

        self.last_pos = self.true_pos.copy()
        self.last_vel = self.true_vel.copy()
        return dt

    
    def get_sensor_readings(self) -> Tuple[Optional[np.ndarray], np.ndarray]:
        imu_reading = self.true_accel + np.random.normal(0, self.imu_noise_std, 2)
        if time.time() - self.gps_last_time >= 1.0 / self.gps_freq:
            self.gps_last_time = time.time()
            gps_reading = self.true_pos + np.random.normal(0, self.gps_noise_std, 2)
        else:
            gps_reading = None
        return gps_reading, imu_reading
    

    def run_step(self) -> Tuple[Optional[np.ndarray], np.ndarray, float]:
        dt = self.update()
        gps_reading, imu_reading = self.get_sensor_readings()
        return gps_reading, imu_reading, dt

    def record_step(self, gps_reading: Optional[np.ndarray], imu_reading: np.ndarray, dt: float) -> None:
        """Record a step: agent state and sensor readings."""
        self.records.append({
            "dt": float(dt),
            "true_pos": [float(self.true_pos[0]), float(self.true_pos[1])],
            "imu": [float(imu_reading[0]), float(imu_reading[1])],
            "gps": None if gps_reading is None else [float(gps_reading[0]), float(gps_reading[1])]
        })

    def save_recording(self, out_path: str, clear: bool = True) -> None:
        """Save recorded data to JSON file."""
        meta = {
            "width": int(self.width),
            "height": int(self.height),
            "gps_freq": float(self.gps_freq),
            "gps_noise_std": float(self.gps_noise_std),
            "imu_noise_std": float(self.imu_noise_std)
        }
        with open(out_path, "w") as f:
            json.dump({"meta": meta, "steps": self.records}, f)
        print(f"Saved recording to {out_path} ({len(self.records)} steps)")
        if clear:
            self.records = []

